import { createSandboxSessionEnv } from '@flue/runtime';
import type { FileStat, SandboxApi, SandboxFactory, SessionEnv, ShellResult } from '@flue/runtime';
import type { Sandbox as DaytonaSandbox } from '@daytona/sdk';

/**
 * Adapts an already-created Daytona sandbox from `@daytona/sdk` into Flue's
 * sandbox interface. It does NOT choose the sandbox's image, identity,
 * retention, or cleanup — your application owns the full lifecycle and passes a
 * ready sandbox in (see src/channels/slack.ts, which creates one box per Slack
 * thread). This file only translates Flue's SandboxApi calls into Daytona SDK
 * calls.
 *
 * Generated by `flue add sandbox daytona` and then adapted for this example.
 */

/** Daytona's command runner merges stderr into `result`; map exit code + stdout. */
function toShellResult(res: { exitCode: number; result: string }): ShellResult {
	return { exitCode: res.exitCode, stdout: res.result ?? '', stderr: '' };
}

/** Map Daytona's FileInfo onto Flue's FileStat. */
function toFileStat(info: { isDir: boolean; size: number; modifiedAt?: string }): FileStat {
	return {
		isFile: !info.isDir,
		isDirectory: info.isDir,
		size: info.size,
		...(info.modifiedAt ? { mtime: new Date(info.modifiedAt) } : {}),
	};
}

function sandboxApi(sandbox: DaytonaSandbox): SandboxApi {
	const fs = sandbox.fs;
	return {
		async readFile(path) {
			return (await fs.downloadFile(path)).toString('utf8');
		},
		async readFileBuffer(path) {
			return new Uint8Array(await fs.downloadFile(path));
		},
		async writeFile(path, content) {
			// FlueFs.writeFile guarantees missing parents are created.
			const slash = path.lastIndexOf('/');
			if (slash > 0) await fs.createFolder(path.slice(0, slash), '755');
			const buf =
				typeof content === 'string' ? Buffer.from(content, 'utf8') : Buffer.from(content);
			await fs.uploadFile(buf, path);
		},
		async stat(path) {
			return toFileStat(await fs.getFileDetails(path));
		},
		async readdir(path) {
			return (await fs.listFiles(path)).map((f) => f.name);
		},
		async exists(path) {
			try {
				await fs.getFileDetails(path);
				return true;
			} catch {
				return false;
			}
		},
		async mkdir(path) {
			// Daytona's createFolder already creates intermediate directories.
			await fs.createFolder(path, '755');
		},
		async rm(path, options) {
			// Daytona supports recursive deletion but not force semantics, so
			// reject `force` rather than silently ignoring it.
			if (options?.force) {
				throw new Error('Daytona sandbox rm does not support { force: true }');
			}
			await fs.deleteFile(path, options?.recursive ?? false);
		},
		async exec(command, options) {
			// timeoutMs is the primary deadline contract; Daytona's timeout is in
			// whole seconds, so round up (never down) to preserve the deadline.
			const timeout =
				options?.timeoutMs === undefined ? undefined : Math.ceil(options.timeoutMs / 1000);
			const res = await sandbox.process.executeCommand(
				command,
				options?.cwd,
				options?.env,
				timeout,
			);
			return toShellResult(res);
		},
	};
}

/**
 * Wrap a ready Daytona sandbox as a Flue SandboxFactory. `createSessionEnv` is
 * called once per agent instance; we hand back the same box every time (the
 * application created exactly one per thread), keyed by the sandbox's own work
 * dir so relative paths and skill discovery resolve there.
 */
export function daytona(sandbox: DaytonaSandbox): SandboxFactory {
	return {
		async createSessionEnv(): Promise<SessionEnv> {
			const cwd = (await sandbox.getWorkDir()) ?? '/home/daytona';
			return createSandboxSessionEnv(sandboxApi(sandbox), cwd);
		},
	};
}
